import json
import os
from typing import List, Dict
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from fastapi.middleware.cors import CORSMiddleware

# LangChain Imports
from langchain_community.llms import Ollama
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# 初始化 FastAPI
app = FastAPI(
    title="Geo-Decision Matrix AI",
    description="Based on Spark Analysis of 1M+ Logistics Datapoints",
    version="2.0.0"
)

# 允許跨域 (讓你的 React 前端可以呼叫)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# 1. 載入 Spark 分析後的知識庫 (The Knowledge)
# ==========================================
def load_risk_knowledge_base() -> str:
    """
    讀取由 PySpark ETL 流程產出的地理誤差統計數據。
    這些數據已經去識別化，僅包含：城市、平均誤差距離(米)、高風險單量佔比。
    """
    file_path = "data/map_risk_summary.json"
    
    # 如果檔案不存在 (本地測試還沒跑 Spark)，先給一個 Mock 數據
    if not os.path.exists(file_path):
        return json.dumps([
            {"city": "Taipei", "avg_error_meters": 8.5, "risk_rate": 0.02, "verdict": "SAFE"},
            {"city": "Changhua", "avg_error_meters": 145.2, "risk_rate": 0.35, "verdict": "RISKY"},
            {"city": "Kaohsiung", "avg_error_meters": 25.1, "risk_rate": 0.12, "verdict": "MONITOR"},
        ], indent=2)

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            # 將 JSON 轉為字串，準備注入 Prompt
            return json.dumps(data, ensure_ascii=False, indent=2)
    except Exception as e:
        return f"Error loading data: {str(e)}"

# 預先載入數據 (模擬 RAG 的 Retrieve 階段)
RISK_CONTEXT = load_risk_knowledge_base()

# ==========================================
# 2. 設定 AI 模型與 Prompt (The Brain)
# ==========================================
# 使用本地運行的 Llama 3
llm = Ollama(model="llama3", base_url="http://host.docker.internal:11434")

# 定義 "Staff Engineer" 等級的 System Prompt
# 關鍵：賦予它「技術決策顧問」的角色，並設定嚴格的風險標準
template = """
You are a Senior Technical Decision Advisor for a large-scale logistics platform.
We are evaluating replacing our current Map Provider (Provider A) with a cost-effective alternative (Provider B).

I will provide you with a statistical summary generated by our Spark cluster, which analyzed 1 million historical delivery coordinates.
The data compares the geolocation difference between Provider A and Provider B.

### Risk Definition:
- **Low Risk**: Avg error < 20m, Risk Rate < 5% (Safe to switch)
- **Medium Risk**: Avg error 20-50m (Need manual review)
- **High Risk**: Avg error > 50m OR Risk Rate > 20% (Do NOT switch)

### Data Summary (from Spark):
{risk_context}

### User Question:
{question}

---
### Instructions:
1. Analyze the specific city or region mentioned in the question based on the Data Summary.
2. Provide a clear **"Go / No-Go"** recommendation.
3. Use professional, data-driven language (e.g., "Based on the 35% risk variance...").
4. **Do NOT** mention any specific company names (like Nidin, Uber, etc.). Refer to us as "the Platform".
5. Answer in **Traditional Chinese (繁體中文)**.
"""

prompt = PromptTemplate(
    template=template,
    input_variables=["question"],
    partial_variables={"risk_context": RISK_CONTEXT} # 預先注入 Spark 數據
)

# 建立處理鏈: Prompt -> LLM -> String Output
chain = prompt | llm | StrOutputParser()

# ==========================================
# 3. 定義 API 介面
# ==========================================
class AnalysisRequest(BaseModel):
    query: str = Field(..., description="E.g., 請問彰化地區適合切換地圖商嗎？")

class AnalysisResponse(BaseModel):
    analysis: str
    data_source_timestamp: str = "2025-12-19 (Spark Job #9527)"

@app.post("/api/v1/consult", response_model=AnalysisResponse)
async def consult_ai(request: AnalysisRequest):
    """
    AI 決策顧問接口
    接收自然語言問題，回傳基於數據的決策建議。
    """
    print(f"🤔 Thinking about: {request.query}")
    try:
        # 呼叫 Llama 3
        result = chain.invoke({"question": request.query})
        return AnalysisResponse(analysis=result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
def health_check():
    return {"status": "active", "model": "Llama 3", "data_source": "Spark ETL"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)